export const GET_ENROLLMENTS_REQUEST = "GET_ENROLLMENTS_REQUEST";
export const GET_ENROLLMENTS_SUCCESS = "GET_ENROLLMENTS_SUCCESS";
export const GET_ENROLLMENTS_FAIL = "GET_ENROLLMENTS_FAIL";
export const ENROLLMENT_LIST_REQUEST = "ENROLLMENT_LIST_REQUEST";
export const ENROLLMENT_LIST_SUCCESS = "ENROLLMENT_LIST_SUCCESS";
export const ENROLLMENT_LIST_FAIL = "ENROLLMENT_LIST_FAIL";

export const ENROLLMENT_CREATE_REQUEST = "ENROLLMENT_CREATE_REQUEST";
export const ENROLLMENT_CREATE_SUCCESS = "ENROLLMENT_CREATE_SUCCESS";
export const ENROLLMENT_CREATE_FAIL = "ENROLLMENT_CREATE_FAIL";

export const ENROLLMENT_DELETE_REQUEST = "ENROLLMENT_DELETE_REQUEST";
export const ENROLLMENT_DELETE_SUCCESS = "ENROLLMENT_DELETE_SUCCESS";
export const ENROLLMENT_DELETE_FAIL = "ENROLLMENT_DELETE_FAIL";
