export const GET_GRADES_REQUEST = "GET_GRADES_REQUEST";
export const GET_GRADES_SUCCESS = "GET_GRADES_SUCCESS";
export const GET_GRADES_FAILURE = "GET_GRADES_FAILURE";

export const CREATE_GRADE_REQUEST = "CREATE_GRADE_REQUEST";
export const CREATE_GRADE_SUCCESS = "CREATE_GRADE_SUCCESS";
export const CREATE_GRADE_FAILURE = "CREATE_GRADE_FAILURE";
